[package]
name = "flash_taskbar_app"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.5"
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
log = "0.4.22"
env_logger = "0.11.5"
image = "0.25.5"
